class AchievementDefinition {
  const AchievementDefinition({
    required this.id,
    required this.title,
    required this.description,
    required this.kind,
    required this.target,
    required this.reward,
  });

  final String id;
  final String title;
  final String description;
  final String kind;
  final int target;
  final int reward;
}

abstract final class AchievementCatalog {
  static const List<AchievementDefinition> all = [
    AchievementDefinition(
      id: 'first_cut',
      title: 'İlk Kıvılcım',
      description: 'İlk cevherini çıkar.',
      kind: 'mine',
      target: 1,
      reward: 25,
    ),
    AchievementDefinition(
      id: 'ore_100',
      title: 'Damar Takipçisi',
      description: '100 cevher çıkar.',
      kind: 'mine',
      target: 100,
      reward: 120,
    ),
    AchievementDefinition(
      id: 'ore_1000',
      title: 'Maden Ustası',
      description: '1.000 cevher çıkar.',
      kind: 'mine',
      target: 1000,
      reward: 650,
    ),
    AchievementDefinition(
      id: 'depth_1k',
      title: 'Yer Kabuğu',
      description: '1 km derinliğe ulaş.',
      kind: 'depth',
      target: 1000,
      reward: 140,
    ),
    AchievementDefinition(
      id: 'depth_10k',
      title: 'On Kilometre',
      description: '10 km derinliğe ulaş.',
      kind: 'depth',
      target: 10000,
      reward: 700,
    ),
    AchievementDefinition(
      id: 'depth_100k',
      title: 'Sessiz Katman',
      description: '100 km derinliğe ulaş.',
      kind: 'depth',
      target: 100000,
      reward: 2400,
    ),
    AchievementDefinition(
      id: 'depth_500k',
      title: 'Çekirdek Sinyali',
      description: '500 km derinliğe ulaş.',
      kind: 'depth',
      target: 500000,
      reward: 8000,
    ),
    AchievementDefinition(
      id: 'crew_5',
      title: 'Tam Vardiya',
      description: 'Beş madenci çalıştır.',
      kind: 'crew',
      target: 5,
      reward: 200,
    ),
    AchievementDefinition(
      id: 'crew_25',
      title: 'Kuyu Ekibi',
      description: '25 madenci çalıştır.',
      kind: 'crew',
      target: 25,
      reward: 1200,
    ),
    AchievementDefinition(
      id: 'sale_1k',
      title: 'İlk Kazanç',
      description: '1.000 kasa değerinde kaynak sat.',
      kind: 'sale',
      target: 1000,
      reward: 250,
    ),
    AchievementDefinition(
      id: 'sale_100k',
      title: 'Ticaret Ağı',
      description: '100.000 kasa değerinde kaynak sat.',
      kind: 'sale',
      target: 100000,
      reward: 2600,
    ),
    AchievementDefinition(
      id: 'chest_1',
      title: 'Gömülü Hatıra',
      description: 'Bir sandık aç.',
      kind: 'chest',
      target: 1,
      reward: 120,
    ),
    AchievementDefinition(
      id: 'chest_10',
      title: 'Kasa Koleksiyoncusu',
      description: '10 sandık aç.',
      kind: 'chest',
      target: 10,
      reward: 900,
    ),
    AchievementDefinition(
      id: 'cave_1',
      title: 'Harita Çizgisi',
      description: 'İlk mağara seferini tamamla.',
      kind: 'cave',
      target: 1,
      reward: 300,
    ),
    AchievementDefinition(
      id: 'cave_10',
      title: 'Derin Kâşif',
      description: '10 mağara seferini tamamla.',
      kind: 'cave',
      target: 10,
      reward: 1300,
    ),
    AchievementDefinition(
      id: 'relic_1',
      title: 'Eski Yazıt',
      description: 'Bir kalıntı bul.',
      kind: 'relic',
      target: 1,
      reward: 250,
    ),
    AchievementDefinition(
      id: 'relic_6',
      title: 'Arşiv Bekçisi',
      description: 'Altı kalıntı bul.',
      kind: 'relic',
      target: 6,
      reward: 1100,
    ),
    AchievementDefinition(
      id: 'boss_1',
      title: 'Taş Muhafızı',
      description: 'Bir muhafızı yen.',
      kind: 'boss',
      target: 1,
      reward: 550,
    ),
    AchievementDefinition(
      id: 'boss_6',
      title: 'Kuyu Efsanesi',
      description: 'Altı muhafızı yen.',
      kind: 'boss',
      target: 6,
      reward: 4000,
    ),
    AchievementDefinition(
      id: 'resonance_1',
      title: 'Katman Yankısı',
      description: 'Bir rezonans dizisini tamamla.',
      kind: 'resonance',
      target: 1,
      reward: 180,
    ),
    AchievementDefinition(
      id: 'resonance_10',
      title: 'Damar Orkestratörü',
      description: '10 rezonans dizisi tamamla.',
      kind: 'resonance',
      target: 10,
      reward: 1400,
    ),
    AchievementDefinition(
      id: 'prestige_1',
      title: 'İkinci Vardiya',
      description: 'Çekirdek döngüsünü bir kez yenile.',
      kind: 'prestige',
      target: 1,
      reward: 750,
    ),
    AchievementDefinition(
      id: 'world_moon',
      title: 'Ay Madencisi',
      description: 'Ay katmanlarına ulaş.',
      kind: 'world',
      target: 1032000,
      reward: 3000,
    ),
    AchievementDefinition(
      id: 'world_titan',
      title: 'Titan Kaşifi',
      description: 'Titan katmanlarına ulaş.',
      kind: 'world',
      target: 1782000,
      reward: 5000,
    ),
    AchievementDefinition(
      id: 'titan_last_layer',
      title: 'Titan’ın Son Katmanı',
      description: '2.566 km derinliğe ulaş.',
      kind: 'depth',
      target: 2566000,
      reward: 30000,
    ),
  ];
}
