import 'mr_mine_progression.dart';
import 'mr_mine_level_table.dart';

enum ResourceKind { mineral, isotope, material, currency, relic }

class ResourceDefinition {
  const ResourceDefinition({
    required this.id,
    required this.name,
    required this.kind,
    required this.baseValue,
    required this.minDepthMeters,
    required this.colorHex,
    required this.iconIndex,
    this.weight = 1,
  });

  final String id;
  final String name;
  final ResourceKind kind;
  final double baseValue;
  final double minDepthMeters;
  final int colorHex;
  final int iconIndex;
  final int weight;

  /// Mr. Mine counts normal minerals and only tier-one isotopes against cargo.
  bool get countsTowardsCapacityAndValue {
    if (kind == ResourceKind.mineral) return true;
    if (kind != ResourceKind.isotope) return false;
    final tieredIsotope = RegExp(r'^(?:u|pu|po|n|he|h|o|e|f)([1-3])$')
        .firstMatch(id);
    return tieredIsotope == null || tieredIsotope.group(1) == '1';
  }

  /// Returns the isotope tier (1, 2, or 3) for tiered isotopes, or 0 otherwise.
  int get isotopeTier {
    if (kind != ResourceKind.isotope) return 0;
    final match = RegExp(r'^(?:u|pu|po|n|he|h|o|e|f)([1-3])$').firstMatch(id);
    return match == null ? 0 : int.parse(match.group(1)!);
  }
}

abstract final class ResourceCatalog {
  static const List<ResourceDefinition> minerals = [
    ResourceDefinition(
      id: 'coal',
      name: 'Kömür',
      kind: ResourceKind.mineral,
      baseValue: 1,
      minDepthMeters: 0,
      colorHex: 0xFF39363A,
      iconIndex: 0,
    ),
    ResourceDefinition(
      id: 'copper',
      name: 'Bakır',
      kind: ResourceKind.mineral,
      baseValue: 2,
      minDepthMeters: 4000,
      colorHex: 0xFFCD743A,
      iconIndex: 1,
    ),
    ResourceDefinition(
      id: 'iron',
      name: 'Demir',
      kind: ResourceKind.mineral,
      baseValue: 6,
      minDepthMeters: 80,
      colorHex: 0xFFADB4B8,
      iconIndex: 2,
    ),
    ResourceDefinition(
      id: 'gold',
      name: 'Altın',
      kind: ResourceKind.mineral,
      baseValue: 16,
      minDepthMeters: 17000,
      colorHex: 0xFFF6C84A,
      iconIndex: 3,
    ),
    ResourceDefinition(
      id: 'emerald',
      name: 'Zümrüt Kristali',
      kind: ResourceKind.mineral,
      baseValue: 18,
      minDepthMeters: 500,
      colorHex: 0xFF31D6C5,
      iconIndex: 4,
    ),
    ResourceDefinition(
      id: 'sapphire',
      name: 'Safir Kristali',
      kind: ResourceKind.mineral,
      baseValue: 22,
      minDepthMeters: 850,
      colorHex: 0xFF389BFF,
      iconIndex: 5,
    ),
    ResourceDefinition(
      id: 'amethyst',
      name: 'Ametist',
      kind: ResourceKind.mineral,
      baseValue: 27,
      minDepthMeters: 1300,
      colorHex: 0xFFB64EFF,
      iconIndex: 6,
    ),
    ResourceDefinition(
      id: 'uranium',
      name: 'Uranyum',
      kind: ResourceKind.mineral,
      baseValue: 35,
      minDepthMeters: 2200,
      colorHex: 0xFF8EE83E,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'silver',
      name: 'Gümüş',
      kind: ResourceKind.mineral,
      baseValue: 4,
      minDepthMeters: 13000,
      colorHex: 0xFFCED7DF,
      iconIndex: 2,
    ),
    ResourceDefinition(
      id: 'quartz',
      name: 'Kuvars',
      kind: ResourceKind.mineral,
      baseValue: 45,
      minDepthMeters: 5000,
      colorHex: 0xFF9EEFFF,
      iconIndex: 5,
    ),
    ResourceDefinition(
      id: 'cobalt',
      name: 'Kobalt',
      kind: ResourceKind.mineral,
      baseValue: 56,
      minDepthMeters: 7500,
      colorHex: 0xFF388DDA,
      iconIndex: 5,
    ),
    ResourceDefinition(
      id: 'ruby',
      name: 'Yakut',
      kind: ResourceKind.mineral,
      baseValue: 68,
      minDepthMeters: 10000,
      colorHex: 0xFFE64F69,
      iconIndex: 6,
    ),
    ResourceDefinition(
      id: 'platinum',
      name: 'Platin',
      kind: ResourceKind.mineral,
      baseValue: 32,
      minDepthMeters: 21000,
      colorHex: 0xFFB8D2DB,
      iconIndex: 2,
    ),
    ResourceDefinition(
      id: 'diamond',
      name: 'Elmas Cevheri',
      kind: ResourceKind.mineral,
      baseValue: 64,
      minDepthMeters: 30000,
      colorHex: 0xFF94E8F3,
      iconIndex: 5,
    ),
    ResourceDefinition(
      id: 'obsidian',
      name: 'Obsidyen',
      kind: ResourceKind.mineral,
      baseValue: 96,
      minDepthMeters: 24000,
      colorHex: 0xFF54465F,
      iconIndex: 6,
    ),
    ResourceDefinition(
      id: 'titanium',
      name: 'Titanyum',
      kind: ResourceKind.mineral,
      baseValue: 115,
      minDepthMeters: 36000,
      colorHex: 0xFFA8AFB5,
      iconIndex: 8,
    ),
    ResourceDefinition(
      id: 'coltan',
      name: 'Koltan',
      kind: ResourceKind.mineral,
      baseValue: 500,
      minDepthMeters: 45000,
      colorHex: 0xFF707B84,
      iconIndex: 2,
    ),
    ResourceDefinition(
      id: 'oil_shale',
      name: 'Petrol Şisti',
      kind: ResourceKind.mineral,
      baseValue: 130,
      minDepthMeters: 50000,
      colorHex: 0xFF3C4145,
      iconIndex: 9,
    ),
    ResourceDefinition(
      id: 'painite',
      name: 'Painit',
      kind: ResourceKind.mineral,
      baseValue: 1000,
      minDepthMeters: 60000,
      colorHex: 0xFFD36E55,
      iconIndex: 6,
    ),
    ResourceDefinition(
      id: 'opal',
      name: 'Opal',
      kind: ResourceKind.mineral,
      baseValue: 154,
      minDepthMeters: 70000,
      colorHex: 0xFF5AD6CE,
      iconIndex: 4,
    ),
    ResourceDefinition(
      id: 'black_opal',
      name: 'Siyah Opal',
      kind: ResourceKind.mineral,
      baseValue: 2000,
      minDepthMeters: 79000,
      colorHex: 0xFF5E4B70,
      iconIndex: 6,
    ),
    ResourceDefinition(
      id: 'amber',
      name: 'Kehribar Taşı',
      kind: ResourceKind.mineral,
      baseValue: 175,
      minDepthMeters: 95000,
      colorHex: 0xFFF2A52D,
      iconIndex: 3,
    ),
    ResourceDefinition(
      id: 'red_diamond',
      name: 'Kızıl Elmas',
      kind: ResourceKind.mineral,
      baseValue: 10000,
      minDepthMeters: 80000,
      colorHex: 0xFFE94D63,
      iconIndex: 6,
    ),
    ResourceDefinition(
      id: 'meteorite',
      name: 'Göktaşı Demiri',
      kind: ResourceKind.mineral,
      baseValue: 210,
      minDepthMeters: 125000,
      colorHex: 0xFF8998A8,
      iconIndex: 2,
    ),
    ResourceDefinition(
      id: 'blue_obsidian',
      name: 'Mavi Obsidyen',
      kind: ResourceKind.mineral,
      baseValue: 20000,
      minDepthMeters: 93000,
      colorHex: 0xFF526BC4,
      iconIndex: 6,
    ),
    ResourceDefinition(
      id: 'star_crystal',
      name: 'Yıldız Kristali',
      kind: ResourceKind.mineral,
      baseValue: 255,
      minDepthMeters: 160000,
      colorHex: 0xFF6CD7FA,
      iconIndex: 5,
    ),
    ResourceDefinition(
      id: 'deep_pearl',
      name: 'Derin İnci',
      kind: ResourceKind.mineral,
      baseValue: 300,
      minDepthMeters: 200000,
      colorHex: 0xFFB9F5E9,
      iconIndex: 4,
    ),
    ResourceDefinition(
      id: 'californium',
      name: 'Kaliforniyum',
      kind: ResourceKind.mineral,
      baseValue: 100000,
      minDepthMeters: 305000,
      colorHex: 0xFF84E96D,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'sunstone',
      name: 'Güneş Taşı',
      kind: ResourceKind.mineral,
      baseValue: 350,
      minDepthMeters: 250000,
      colorHex: 0xFFFFB440,
      iconIndex: 3,
    ),
    ResourceDefinition(
      id: 'void_glass',
      name: 'Boşluk Camı',
      kind: ResourceKind.mineral,
      baseValue: 410,
      minDepthMeters: 310000,
      colorHex: 0xFF7A69E8,
      iconIndex: 6,
    ),
    ResourceDefinition(
      id: 'moon_silver',
      name: 'Ay Gümüşü',
      kind: ResourceKind.mineral,
      baseValue: 490,
      minDepthMeters: 1032000,
      colorHex: 0xFFD7E5F1,
      iconIndex: 2,
    ),
    ResourceDefinition(
      id: 'lunar_ice',
      name: 'Ay Buzu',
      kind: ResourceKind.mineral,
      baseValue: 560,
      minDepthMeters: 1040000,
      colorHex: 0xFF7BD7FF,
      iconIndex: 5,
    ),
    ResourceDefinition(
      id: 'selenite',
      name: 'Selenit',
      kind: ResourceKind.mineral,
      baseValue: 650,
      minDepthMeters: 1080000,
      colorHex: 0xFFF1E7D4,
      iconIndex: 8,
    ),
    ResourceDefinition(
      id: 'helium_ore',
      name: 'Helyum Cevheri',
      kind: ResourceKind.mineral,
      baseValue: 770,
      minDepthMeters: 1132000,
      colorHex: 0xFF73DBDE,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'carbon',
      name: 'Karbon',
      kind: ResourceKind.mineral,
      baseValue: 500000,
      minDepthMeters: 1032000,
      colorHex: 0xFF647582,
      iconIndex: 9,
    ),
    ResourceDefinition(
      id: 'moon_iron',
      name: 'Ay Demiri',
      kind: ResourceKind.mineral,
      baseValue: 1000000,
      minDepthMeters: 1041000,
      colorHex: 0xFFADB4B8,
      iconIndex: 2,
    ),
    ResourceDefinition(
      id: 'aluminum',
      name: 'Alüminyum',
      kind: ResourceKind.mineral,
      baseValue: 2000000,
      minDepthMeters: 1042000,
      colorHex: 0xFFC5D0DC,
      iconIndex: 2,
    ),
    ResourceDefinition(
      id: 'magnesium',
      name: 'Magnezyum',
      kind: ResourceKind.mineral,
      baseValue: 5000000,
      minDepthMeters: 1125000,
      colorHex: 0xFF80D1A2,
      iconIndex: 4,
    ),
    ResourceDefinition(
      id: 'lunar_titanium',
      name: 'Ay Titanyumu',
      kind: ResourceKind.mineral,
      baseValue: 750000000,
      minDepthMeters: 1211000,
      colorHex: 0xFFA8AFB5,
      iconIndex: 8,
    ),
    ResourceDefinition(
      id: 'silicon',
      name: 'Silisyum',
      kind: ResourceKind.mineral,
      baseValue: 100000000,
      minDepthMeters: 1333000,
      colorHex: 0xFF9AC2D8,
      iconIndex: 5,
    ),
    ResourceDefinition(
      id: 'promethium',
      name: 'Prometyum',
      kind: ResourceKind.mineral,
      baseValue: 1400000000,
      minDepthMeters: 1462000,
      colorHex: 0xFF9BE76B,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'neodymium',
      name: 'Neodimyum',
      kind: ResourceKind.mineral,
      baseValue: 10000000000,
      minDepthMeters: 1562000,
      colorHex: 0xFF8A76D8,
      iconIndex: 6,
    ),
    ResourceDefinition(
      id: 'ytterbium',
      name: 'İterbiyum',
      kind: ResourceKind.mineral,
      baseValue: 50000000000,
      minDepthMeters: 1605000,
      colorHex: 0xFF9ED2D6,
      iconIndex: 5,
    ),
    ResourceDefinition(
      id: 'titan_ice',
      name: 'Titan Buzu',
      kind: ResourceKind.mineral,
      baseValue: 920,
      minDepthMeters: 1814000,
      colorHex: 0xFF5E9FE4,
      iconIndex: 5,
    ),
    ResourceDefinition(
      id: 'methane_crystal',
      name: 'Metan Kristali',
      kind: ResourceKind.mineral,
      baseValue: 1080,
      minDepthMeters: 1814000,
      colorHex: 0xFF83C5F4,
      iconIndex: 4,
    ),
    ResourceDefinition(
      id: 'hydrogen_ore',
      name: 'Hidrojen Cevheri',
      kind: ResourceKind.mineral,
      baseValue: 1000,
      minDepthMeters: 1814000,
      colorHex: 0xFFDCA77C,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'oxygen_crystal',
      name: 'Oksijen Kristali',
      kind: ResourceKind.mineral,
      baseValue: 1060,
      minDepthMeters: 1814000,
      colorHex: 0xFFB5F7F0,
      iconIndex: 5,
    ),
    ResourceDefinition(
      id: 'lithium',
      name: 'Lityum',
      kind: ResourceKind.mineral,
      baseValue: 10000000000000.0,
      minDepthMeters: 1878000,
      colorHex: 0xFFD7A3C7,
      iconIndex: 4,
    ),
    ResourceDefinition(
      id: 'tin',
      name: 'Kalay',
      kind: ResourceKind.mineral,
      baseValue: 500000000000.0,
      minDepthMeters: 1814000,
      colorHex: 0xFFB7C1C7,
      iconIndex: 2,
    ),
    ResourceDefinition(
      id: 'corestone',
      name: 'Çekirdek Taşı',
      kind: ResourceKind.mineral,
      baseValue: 1400,
      minDepthMeters: 2200000,
      colorHex: 0xFFDF6946,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'sulfur',
      name: 'Kükürt',
      kind: ResourceKind.mineral,
      baseValue: 2500000000000.0,
      minDepthMeters: 1854000,
      colorHex: 0xFFE9D953,
      iconIndex: 3,
    ),
    ResourceDefinition(
      id: 'manganese',
      name: 'Manganez',
      kind: ResourceKind.mineral,
      baseValue: 750000000000000.0,
      minDepthMeters: 2015000,
      colorHex: 0xFF8E78A8,
      iconIndex: 2,
    ),
    ResourceDefinition(
      id: 'mercury',
      name: 'Cıva',
      kind: ResourceKind.mineral,
      baseValue: 7500000000000000.0,
      minDepthMeters: 2142000,
      colorHex: 0xFFCAD4D8,
      iconIndex: 2,
    ),
    ResourceDefinition(
      id: 'nickel',
      name: 'Nikel',
      kind: ResourceKind.mineral,
      baseValue: 75000000000000000.0,
      minDepthMeters: 2242000,
      colorHex: 0xFF91A994,
      iconIndex: 2,
    ),
    ResourceDefinition(
      id: 'alexandrite',
      name: 'Aleksandrit',
      kind: ResourceKind.mineral,
      baseValue: 1.25e18,
      minDepthMeters: 2317000,
      colorHex: 0xFF55B8A5,
      iconIndex: 4,
    ),
    ResourceDefinition(
      id: 'benitoite',
      name: 'Benitoit',
      kind: ResourceKind.mineral,
      baseValue: 1.25e19,
      minDepthMeters: 2414000,
      colorHex: 0xFF4C8AE8,
      iconIndex: 5,
    ),
    ResourceDefinition(
      id: 'titan_cobalt',
      name: 'Titan Kobaltı',
      kind: ResourceKind.mineral,
      baseValue: 6e19,
      minDepthMeters: 2500000,
      colorHex: 0xFF388DDA,
      iconIndex: 5,
    ),
  ];

  static const List<ResourceDefinition> isotopes = [
    ResourceDefinition(
      id: 'iso_hydrogen',
      name: 'Hidrojen İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 80,
      minDepthMeters: 12000,
      colorHex: 0xFF70D8E0,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_oxygen',
      name: 'Oksijen İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 95,
      minDepthMeters: 18000,
      colorHex: 0xFFB5F7F0,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_carbon',
      name: 'Karbon İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 110,
      minDepthMeters: 24000,
      colorHex: 0xFF647582,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_nitrogen',
      name: 'Azot İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 125,
      minDepthMeters: 32000,
      colorHex: 0xFF8DB9D7,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_neon',
      name: 'Neon İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 145,
      minDepthMeters: 42000,
      colorHex: 0xFFFF8271,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_sodium',
      name: 'Sodyum İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 160,
      minDepthMeters: 54000,
      colorHex: 0xFFFFD56F,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_magnesium',
      name: 'Magnezyum İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 180,
      minDepthMeters: 68000,
      colorHex: 0xFF80D1A2,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_aluminium',
      name: 'Alüminyum İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 205,
      minDepthMeters: 84000,
      colorHex: 0xFFC5D0DC,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_silicon',
      name: 'Silisyum İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 225,
      minDepthMeters: 102000,
      colorHex: 0xFF9AC2D8,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_sulfur',
      name: 'Kükürt İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 250,
      minDepthMeters: 124000,
      colorHex: 0xFFE9D953,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_chlorine',
      name: 'Klor İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 280,
      minDepthMeters: 148000,
      colorHex: 0xFFB5E866,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_argon',
      name: 'Argon İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 315,
      minDepthMeters: 174000,
      colorHex: 0xFFB490E7,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_potassium',
      name: 'Potasyum İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 350,
      minDepthMeters: 202000,
      colorHex: 0xFFDCA77C,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_calcium',
      name: 'Kalsiyum İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 390,
      minDepthMeters: 232000,
      colorHex: 0xFFEDE5D1,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_scandium',
      name: 'Skandiyum İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 430,
      minDepthMeters: 264000,
      colorHex: 0xFF76BFB9,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_titanium',
      name: 'Titanyum İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 475,
      minDepthMeters: 298000,
      colorHex: 0xFFB3BBC9,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_vanadium',
      name: 'Vanadyum İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 525,
      minDepthMeters: 334000,
      colorHex: 0xFF568BC8,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_chromium',
      name: 'Krom İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 580,
      minDepthMeters: 372000,
      colorHex: 0xFFD5DDE3,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_manganese',
      name: 'Manganez İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 640,
      minDepthMeters: 412000,
      colorHex: 0xFF8E78A8,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_iron',
      name: 'Demir İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 705,
      minDepthMeters: 454000,
      colorHex: 0xFFD17D54,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_cobalt',
      name: 'Kobalt İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 775,
      minDepthMeters: 498000,
      colorHex: 0xFF5796DE,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_nickel',
      name: 'Nikel İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 850,
      minDepthMeters: 544000,
      colorHex: 0xFF9EB7A7,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_copper',
      name: 'Bakır İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 930,
      minDepthMeters: 592000,
      colorHex: 0xFFD58A4C,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_zinc',
      name: 'Çinko İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 1020,
      minDepthMeters: 642000,
      colorHex: 0xFF8CB5B0,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_gallium',
      name: 'Galyum İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 1115,
      minDepthMeters: 694000,
      colorHex: 0xFF9BAFE8,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_germanium',
      name: 'Germanyum İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 1220,
      minDepthMeters: 748000,
      colorHex: 0xFF8996C3,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'iso_krypton',
      name: 'Kripton İzotopu',
      kind: ResourceKind.isotope,
      baseValue: 1350,
      minDepthMeters: 804000,
      colorHex: 0xFFBE81D8,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'u1',
      name: 'Uranyum I',
      kind: ResourceKind.isotope,
      baseValue: 100,
      minDepthMeters: 24000,
      colorHex: 0xFF8EE83E,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'u2',
      name: 'Uranyum II',
      kind: ResourceKind.isotope,
      baseValue: 2000,
      minDepthMeters: 24000,
      colorHex: 0xFFA0E957,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'u3',
      name: 'Uranyum III',
      kind: ResourceKind.isotope,
      baseValue: 50000,
      minDepthMeters: 24000,
      colorHex: 0xFFC3F26A,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'pu1',
      name: 'Plütonyum I',
      kind: ResourceKind.isotope,
      baseValue: 1000,
      minDepthMeters: 34000,
      colorHex: 0xFFD7E56B,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'pu2',
      name: 'Plütonyum II',
      kind: ResourceKind.isotope,
      baseValue: 20000,
      minDepthMeters: 34000,
      colorHex: 0xFFE3D86A,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'pu3',
      name: 'Plütonyum III',
      kind: ResourceKind.isotope,
      baseValue: 500000,
      minDepthMeters: 34000,
      colorHex: 0xFFE7C85F,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'po1',
      name: 'Polonyum I',
      kind: ResourceKind.isotope,
      baseValue: 5000,
      minDepthMeters: 54000,
      colorHex: 0xFFFF8271,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'po2',
      name: 'Polonyum II',
      kind: ResourceKind.isotope,
      baseValue: 250000,
      minDepthMeters: 54000,
      colorHex: 0xFFF58D7F,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'po3',
      name: 'Polonyum III',
      kind: ResourceKind.isotope,
      baseValue: 50000000,
      minDepthMeters: 54000,
      colorHex: 0xFFE7758C,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'n1',
      name: 'Azot I',
      kind: ResourceKind.isotope,
      baseValue: 50000000,
      minDepthMeters: 1067000,
      colorHex: 0xFF8DB9D7,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'n2',
      name: 'Azot II',
      kind: ResourceKind.isotope,
      baseValue: 150000000,
      minDepthMeters: 1067000,
      colorHex: 0xFF9DCBE5,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'n3',
      name: 'Azot III',
      kind: ResourceKind.isotope,
      baseValue: 300000000,
      minDepthMeters: 1067000,
      colorHex: 0xFFB1DDF3,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'he1',
      name: 'Helyum I',
      kind: ResourceKind.isotope,
      baseValue: 500000000,
      minDepthMeters: 1132000,
      colorHex: 0xFFFFC887,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'he2',
      name: 'Helyum II',
      kind: ResourceKind.isotope,
      baseValue: 5000000000,
      minDepthMeters: 1132000,
      colorHex: 0xFFFFD79B,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'he3',
      name: 'Helyum III',
      kind: ResourceKind.isotope,
      baseValue: 500000000000,
      minDepthMeters: 1132000,
      colorHex: 0xFFFFE6B0,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'h1',
      name: 'Hidrojen I',
      kind: ResourceKind.isotope,
      baseValue: 50000,
      minDepthMeters: 1849000,
      colorHex: 0xFFDCA77C,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'h2',
      name: 'Hidrojen II',
      kind: ResourceKind.isotope,
      baseValue: 500000,
      minDepthMeters: 1849000,
      colorHex: 0xFFE6BE98,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'h3',
      name: 'Hidrojen III',
      kind: ResourceKind.isotope,
      baseValue: 5000000,
      minDepthMeters: 1849000,
      colorHex: 0xFFFFD6A0,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'o1',
      name: 'Oksijen I',
      kind: ResourceKind.isotope,
      baseValue: 66600,
      minDepthMeters: 1914000,
      colorHex: 0xFFB5F7F0,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'o2',
      name: 'Oksijen II',
      kind: ResourceKind.isotope,
      baseValue: 666000,
      minDepthMeters: 1914000,
      colorHex: 0xFFC6FCF7,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'o3',
      name: 'Oksijen III',
      kind: ResourceKind.isotope,
      baseValue: 6660000,
      minDepthMeters: 1914000,
      colorHex: 0xFFE1FFFC,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'e1',
      name: 'Einsteinyum I',
      kind: ResourceKind.isotope,
      baseValue: 2200,
      minDepthMeters: 1132000,
      colorHex: 0xFF80D843,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'e2',
      name: 'Einsteinyum II',
      kind: ResourceKind.isotope,
      baseValue: 6200,
      minDepthMeters: 1200000,
      colorHex: 0xFFB7E85A,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'e3',
      name: 'Einsteinyum III',
      kind: ResourceKind.isotope,
      baseValue: 15000,
      minDepthMeters: 1250000,
      colorHex: 0xFFE0F270,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'f1',
      name: 'Fermiyum I',
      kind: ResourceKind.isotope,
      baseValue: 3900,
      minDepthMeters: 1150000,
      colorHex: 0xFF5ED5C6,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'f2',
      name: 'Fermiyum II',
      kind: ResourceKind.isotope,
      baseValue: 9800,
      minDepthMeters: 1200000,
      colorHex: 0xFF74ADEF,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'f3',
      name: 'Fermiyum III',
      kind: ResourceKind.isotope,
      baseValue: 24000,
      minDepthMeters: 1250000,
      colorHex: 0xFFB887EE,
      iconIndex: 7,
    ),
  ];

  static const List<ResourceDefinition> materials = [
    ResourceDefinition(
      id: 'building_material',
      name: 'Yapı Malzemesi',
      kind: ResourceKind.material,
      baseValue: 0,
      minDepthMeters: 0,
      colorHex: 0xFFC78A54,
      iconIndex: 10,
    ),
    ResourceDefinition(
      id: 'oil',
      name: 'Petrol',
      kind: ResourceKind.material,
      baseValue: 0,
      minDepthMeters: 50000,
      colorHex: 0xFF49555B,
      iconIndex: 9,
    ),
    ResourceDefinition(
      id: 'nuclear_energy',
      name: 'Nükleer Enerji',
      kind: ResourceKind.material,
      baseValue: 0,
      minDepthMeters: 1132000,
      colorHex: 0xFF8EE83E,
      iconIndex: 7,
    ),
    ResourceDefinition(
      id: 'ticket',
      name: 'Sefer Bileti',
      kind: ResourceKind.material,
      baseValue: 0,
      minDepthMeters: 0,
      colorHex: 0xFFF0A52E,
      iconIndex: 15,
    ),
  ];

  static final List<ResourceDefinition> all = [
    ...minerals,
    ...isotopes,
    ...materials,
  ];
  static final Map<String, ResourceDefinition> byId = {
    for (final resource in all) resource.id: resource,
  };

  /// Uses the live Mr. Mine shaft table for source resources and keeps the
  /// authored fallback only for resources unique to this project.
  static double firstMineDepthMeters(String resourceId) =>
      MrMineLevelTable.firstDepthMetersByResource[resourceId]?.toDouble() ??
      byId[resourceId]?.minDepthMeters ??
      0;

  static ResourceDefinition? mineableAtDepth(double depthMeters) {
    if (MrMineProgression.worldAtDepth(depthMeters) == null) return null;
    final floor = (depthMeters / 1000).floor();
    if (floor < 0 || floor >= MrMineLevelTable.rows.length) return null;
    final resources =
        MrMineLevelTable.rows[floor].entries
            .map((entry) => (byId[entry.key], entry.value))
            .where((entry) => entry.$1?.kind == ResourceKind.mineral)
            .toList(growable: false)
          ..sort((a, b) => b.$2.compareTo(a.$2));
    return resources.isEmpty ? null : resources.first.$1;
  }

  /// Fallback for legacy callers that always need a displayable mineral.
  /// Loot-producing code should use [mineableAtDepth] so transition zones
  /// never award an ore from the wrong world.
  static ResourceDefinition atDepth(double depthMeters) =>
      mineableAtDepth(depthMeters) ?? minerals.first;

  static Iterable<ResourceDefinition> unlockedAt(double depthMeters) sync* {
    final worldIndex = MrMineProgression.worldAtDepth(depthMeters);
    if (worldIndex == null) return;
    final startDepth = switch (worldIndex) {
      0 => 0,
      1 => MrMineProgression.moonStartMeters,
      2 => MrMineProgression.titanStartMeters,
      _ => 0,
    };
    final firstFloor = (startDepth / 1000).floor();
    final finalFloor = (depthMeters / 1000).floor();
    final found = <String>{};
    for (var floor = firstFloor; floor <= finalFloor; floor++) {
      if (floor < 0 || floor >= MrMineLevelTable.rows.length) continue;
      for (final id in MrMineLevelTable.rows[floor].keys) {
        if (!found.add(id)) continue;
        final resource = byId[id];
        if (resource != null) yield resource;
      }
    }
  }

  static int isotopeTier(String id) => byId[id]?.isotopeTier ?? 0;

  static ResourceDefinition? decayedIsotope(String id) {
    final match = RegExp(r'^(u|pu|po|n|he|h|o|e|f)([1-2])$').firstMatch(id);
    if (match == null) return null;
    final prefix = match.group(1)!;
    final nextTier = int.parse(match.group(2)!) + 1;
    return byId['$prefix$nextTier'];
  }
}
